
(load "lib/maximize-editor" nil t)
(load "lib/kill-other-buffer" nil t)
(load "lib/dublicate-line" nil t)
(load "lib/rspec" nil t)
(load "lib/rake" nil t)
(load "lib/redmine" nil t)
(load "lib/add_js_global" nil t)
(load "lib/text_objects" nil t)
(load "lib/xdoc-fill" nil t)
(load "lib/whitespace" nil t)
(load "lib/workspace" nil t)
