(require 'comint)

(defun ensure-multi-term (new-name dir register)
  (if (get-buffer new-name)
      (with-current-buffer new-name
        (point-to-register register))
      (message (format "Buffer '%s' exists" new-name))
    (open-multi-term new-name dir register)))

(defun open-multi-term (new-name dir register)  
  (let ((mt-buffer-name "*auto-terminal<1>*"))
    (setq multi-term-buffer-name "auto-terminal")
    (multi-term)
    (setq multi-term-buffer-name "terminal")
    (comint-send-string (get-buffer-process mt-buffer-name) (format "cd %s\n" dir))
    (with-current-buffer mt-buffer-name
      (rename-buffer new-name)
      (point-to-register register))))

(defun init-pageflow-monorepo-multi-terms ()
  (interactive)
  (ensure-multi-term "*pageflow*" "$HOME/code/gh/pageflow" ?g)
  (ensure-multi-term "*pageflow Build*" "$HOME/code/gh/pageflow" ?G)
  (ensure-multi-term "*pageflow package*" "$HOME/code/gh/pageflow/package" ?p)
  (ensure-multi-term "*pageflow-react package*" "$HOME/code/gh/pageflow/entry_types/paged/packages/pageflow-paged-react" ?R)
  (ensure-multi-term "*pageflow-react Build*" "$HOME/code/gh/pageflow/entry_types/paged/packages/pageflow-paged-react" ?2)
  (ensure-multi-term "*pageflow-paged*" "$HOME/code/gh/pageflow/entry_types/paged" ?c)
  (ensure-multi-term "*pageflow-paged package*" "$HOME/code/gh/pageflow/entry_types/paged/packages/pageflow-paged" ?C)
  (ensure-multi-term "*pageflow-scrolled*" "$HOME/code/gh/pageflow/entry_types/scrolled" ?n)
  (ensure-multi-term "*pageflow-scrolled package*" "$HOME/code/gh/pageflow/entry_types/scrolled/package" ?N)
  (ensure-multi-term "*dedicated*" "$HOME/code/dedicated_pageflow" ?d)
  (ensure-multi-term "*hosted*" "$HOME/code/hosted_pageflow" ?h)
  (ensure-multi-term "*server*" "$HOME/code/dedicated_pageflow" ?s))

(defun init-pageflow-multi-terms ()
  (interactive)
  (ensure-multi-term "*pageflow*" "$HOME/code/gh/pageflow" ?g)
  (ensure-multi-term "*pageflow-analytics*" "$HOME/code/gh/pageflow-analytics" ?a)
  (ensure-multi-term "*pageflow Build*" "$HOME/code/gh/pageflow" ?G)
  (ensure-multi-term "*pageflow-react*" "$HOME/code/gh/pageflow-react/js" ?r)
  (ensure-multi-term "*pageflow-vr*" "$HOME/code/gh/pageflow-vr" ?v)
  (ensure-multi-term "*pageflow-panorama*" "$HOME/code/gh/pageflow-panorama" ?p)
  (ensure-multi-term "*pageflow-before-after*" "$HOME/code/gh/pageflow-before-after" ?b)
  (ensure-multi-term "*pageflow-timeline-page*" "$HOME/code/gh/pageflow-timeline-page" ?T)
  (ensure-multi-term "*pageflow-chart*" "$HOME/code/gh/pageflow-chart" ?c)
  (ensure-multi-term "*pageflow-embedded-video*" "$HOME/code/gh/pageflow-embedded-video" ?e)
  (ensure-multi-term "*pageflow-internal-links*" "$HOME/code/gh/pageflow-internal-links" ?i)
  (ensure-multi-term "*pageflow-linkmap-page*" "$HOME/code/gh/pageflow-linkmap-page" ?l)
  (ensure-multi-term "*pageflow-external-links*" "$HOME/code/gh/pageflow-external-links" ?x)
  (ensure-multi-term "*pageflow-text-page*" "$HOME/code/gh/pageflow-text-page" ?t)
  (ensure-multi-term "*pageflow-public-i18n*" "$HOME/code/gh/pageflow-public-i18n" ?8)
  (ensure-multi-term "*pageflow-new-pages-box*" "$HOME/code/gh/pageflow-new-pages-box" ?n)
  (ensure-multi-term "*pageflow-parent-page-box*" "$HOME/code/gh/pageflow-parent-page-box" ?E)
  (ensure-multi-term "*pageflow-progress-navigation-bar*" "$HOME/code/gh/pageflow-progress-navigation-bar" ?2)
  (ensure-multi-term "*pageflow-outline-navigation-bar*" "$HOME/code/gh/pageflow-outline-navigation-bar" ?o)
  (ensure-multi-term "*dedicated*" "$HOME/code/dedicated_pageflow" ?d)
  (ensure-multi-term "*hosted*" "$HOME/code/hosted_pageflow" ?h)
  (ensure-multi-term "*pageflow-push*" "$HOME/code/gh/pageflow-push" ?P)
  (ensure-multi-term "*cert_watch*" "$HOME/code/gh/cert_watch" ?C)
  (ensure-multi-term "*krant*" "$HOME/code/gh/krant" ?k)
  (ensure-multi-term "*server*" "$HOME/code/dedicated_pageflow" ?s))

(defun init-digit-multi-terms ()
  (interactive)
  (ensure-multi-term "*digit*" "$HOME/code/digit" ?d)
  (ensure-multi-term "*digit_config*" "$HOME/code/digit_config" ?D)
  (ensure-multi-term "*server*" "$HOME/code/digit" ?s))


(defun init-pageflow-push-multi-terms ()
  (interactive)
  (ensure-multi-term "*hosted*" "$HOME/code/hosted_pageflow" ?h)
  (ensure-multi-term "*server*" "$HOME/code/dedicated_pageflow" ?s)
  (ensure-multi-term "*pageflow*" "$HOME/code/gh/pageflow" ?g)
  (ensure-multi-term "*pageflow Build*" "$HOME/code/gh/pageflow/node_package" ?G)
  (ensure-multi-term "*pageflow-push*" "$HOME/code/gh/pageflow-push" ?p)
  (ensure-multi-term "*pageflow-push Build*" "$HOME/code/gh/pageflow-push" ?P))
  
(defun init-quiz-multi-terms ()
  (interactive)
  (ensure-multi-term "*sq_server*" "$HOME/code/sq_server" ?s)
  (ensure-multi-term "*sq_server/client build*" "$HOME/code/sq_server/apps/admin/assets/client" ?C)
  (ensure-multi-term "*sq_server/qdb*" "$HOME/code/sq_server/apps/qdb" ?d)
  (ensure-multi-term "*sq_server phx.server*" "$HOME/code/sq_server" ?S)
  (ensure-multi-term "*sq_server/quiz_server*" "$HOME/code/sq_server/apps/quiz_server" ?q)
  (ensure-multi-term "*sq_app*" "$HOME/code/sq_app" ?a)
  (ensure-multi-term "*sq_app build*" "$HOME/code/sq_app" ?A))
  
