(defun color-theme-custom-dark ()
  (interactive)
  (color-theme-install
   '(color-theme-custom-dark
      ((background-color . "#000000")
      (background-mode . dark)
      (border-color . "#000000")
      (cursor-color . "#ffffff")
      (foreground-color . "#f6f3e8")
      (mouse-color . "black"))
     (fringe ((t (:background "#000000"))))
     (mode-line ((t (:foreground "#cccccc" :background "#202020"))))
     (mode-line-inactive ((t (:foreground "#000000" :background "#202020"))))
     (region ((t (:background "#1D1E2C"))))
     (highlight ((t (:background "skyblue4"))))
     (ido-subdir ((t (:foreground "#aaaaaa"))))
     (anything-isearch-match ((t (:foreground "brown4" :background "palevioletred2"))))
     (font-lock-builtin-face ((t (:foreground "#729fcf"))))
     (font-lock-comment-face ((t (:foreground "#7c7c7c"))))
     (font-lock-function-name-face ((t (:foreground "#ffd2a7"))))
     (font-lock-keyword-face ((t (:foreground "#96cbfe"))))
     (font-lock-string-face ((t (:foreground "#a8ff60"))))
     (font-lock-type-face ((t (:foreground"#ffffb6"))))
     (font-lock-variable-name-face ((t (:foreground "#c6c5fe"))))
     (font-lock-constant-face ((t (:foreground "#99cc99"))))
     (minibuffer-prompt ((t (:foreground "#f6f3e8" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
(provide 'custom-dark)